### ISSUE TITLE
Only run if package-lock.json was staged for commit

### ISSUE THREAD

**Issue by splashdust** [splashdust/package-lock-sanitizer#1]
Add a way to detect if package-lock.json was actually staged before running package-lock-sanitizer.

**Comment by xballoy** [comment]
I do not think it's your package responsibility to check if the package-lock.json was staged. I used lint-staged with the following configuration:
```
  "lint-staged": {
    "package-lock.json": [
      "package-lock-sanitizer -l"
    ]
```

The `-l` parameter is required because lint-staged pass the file name to the command.

**Comment by splashdust** [comment]
@xballoy Yes, I think you are probably right. I will close this issue. Thank you for the feedback!
